// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: orderbot/v1/common.proto

package orderbotv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MenuItemId       string                 `protobuf:"bytes,2,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity         int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceScaled  int32                  `protobuf:"varint,5,opt,name=unit_price_scaled,json=unitPriceScaled,proto3" json:"unit_price_scaled,omitempty"`
	TotalPriceScaled int32                  `protobuf:"varint,6,opt,name=total_price_scaled,json=totalPriceScaled,proto3" json:"total_price_scaled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_orderbot_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orderbot_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_orderbot_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPriceScaled() int32 {
	if x != nil {
		return x.UnitPriceScaled
	}
	return 0
}

func (x *OrderItem) GetTotalPriceScaled() int32 {
	if x != nil {
		return x.TotalPriceScaled
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BotId         string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	CartId        string                 `protobuf:"bytes,3,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalScaled   int32                  `protobuf:"varint,5,opt,name=total_scaled,json=totalScaled,proto3" json:"total_scaled,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orderbot_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbot_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderbot_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *CreateOrderRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CreateOrderRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalScaled() int32 {
	if x != nil {
		return x.TotalScaled
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_orderbot_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbot_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderbot_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type MarkOrderCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderCompletedRequest) Reset() {
	*x = MarkOrderCompletedRequest{}
	mi := &file_orderbot_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderCompletedRequest) ProtoMessage() {}

func (x *MarkOrderCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbot_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderCompletedRequest.ProtoReflect.Descriptor instead.
func (*MarkOrderCompletedRequest) Descriptor() ([]byte, []int) {
	return file_orderbot_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *MarkOrderCompletedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type MarkOrderCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderCompletedResponse) Reset() {
	*x = MarkOrderCompletedResponse{}
	mi := &file_orderbot_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderCompletedResponse) ProtoMessage() {}

func (x *MarkOrderCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbot_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderCompletedResponse.ProtoReflect.Descriptor instead.
func (*MarkOrderCompletedResponse) Descriptor() ([]byte, []int) {
	return file_orderbot_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *MarkOrderCompletedResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_orderbot_v1_common_proto protoreflect.FileDescriptor

const file_orderbot_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18orderbot/v1/common.proto\x12\vorderbot.v1\"\xc7\x01\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\fmenu_item_id\x18\x02 \x01(\tR\n" +
	"menuItemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12*\n" +
	"\x11unit_price_scaled\x18\x05 \x01(\x05R\x0funitPriceScaled\x12,\n" +
	"\x12total_price_scaled\x18\x06 \x01(\x05R\x10totalPriceScaled\"\xcf\x01\n" +
	"\x12CreateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\x12\x17\n" +
	"\acart_id\x18\x03 \x01(\tR\x06cartId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12!\n" +
	"\ftotal_scaled\x18\x05 \x01(\x05R\vtotalScaled\x12,\n" +
	"\x05items\x18\x06 \x03(\v2\x16.orderbot.v1.OrderItemR\x05items\"%\n" +
	"\x13CreateOrderResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"6\n" +
	"\x19MarkOrderCompletedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\",\n" +
	"\x1aMarkOrderCompletedResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02okB@Z>github.com/RockkLee/order-bot/goproto/orderbot/v1;orderbotv1pbb\x06proto3"

var (
	file_orderbot_v1_common_proto_rawDescOnce sync.Once
	file_orderbot_v1_common_proto_rawDescData []byte
)

func file_orderbot_v1_common_proto_rawDescGZIP() []byte {
	file_orderbot_v1_common_proto_rawDescOnce.Do(func() {
		file_orderbot_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderbot_v1_common_proto_rawDesc), len(file_orderbot_v1_common_proto_rawDesc)))
	})
	return file_orderbot_v1_common_proto_rawDescData
}

var file_orderbot_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_orderbot_v1_common_proto_goTypes = []any{
	(*OrderItem)(nil),                  // 0: orderbot.v1.OrderItem
	(*CreateOrderRequest)(nil),         // 1: orderbot.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),        // 2: orderbot.v1.CreateOrderResponse
	(*MarkOrderCompletedRequest)(nil),  // 3: orderbot.v1.MarkOrderCompletedRequest
	(*MarkOrderCompletedResponse)(nil), // 4: orderbot.v1.MarkOrderCompletedResponse
}
var file_orderbot_v1_common_proto_depIdxs = []int32{
	0, // 0: orderbot.v1.CreateOrderRequest.items:type_name -> orderbot.v1.OrderItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orderbot_v1_common_proto_init() }
func file_orderbot_v1_common_proto_init() {
	if File_orderbot_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbot_v1_common_proto_rawDesc), len(file_orderbot_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderbot_v1_common_proto_goTypes,
		DependencyIndexes: file_orderbot_v1_common_proto_depIdxs,
		MessageInfos:      file_orderbot_v1_common_proto_msgTypes,
	}.Build()
	File_orderbot_v1_common_proto = out.File
	file_orderbot_v1_common_proto_goTypes = nil
	file_orderbot_v1_common_proto_depIdxs = nil
}
