# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbot/v1/order_bot_svc/order_status_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orderbot/v1/order_bot_svc/order_status_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orderbot.v1 import common_pb2 as orderbot_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4orderbot/v1/order_bot_svc/order_status_service.proto\x12\x0borderbot.v1\x1a\x18orderbot/v1/common.proto2{\n\x12OrderStatusService\x12\x65\n\x12MarkOrderCompleted\x12&.orderbot.v1.MarkOrderCompletedRequest\x1a\'.orderbot.v1.MarkOrderCompletedResponseBOZMgithub.com/RockkLee/order-bot/goproto/orderbot/v1/order_bot_svc;orderbotsvcpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbot.v1.order_bot_svc.order_status_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/RockkLee/order-bot/goproto/orderbot/v1/order_bot_svc;orderbotsvcpb'
  _globals['_ORDERSTATUSSERVICE']._serialized_start=95
  _globals['_ORDERSTATUSSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
