// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: orderbot/v1/order_bot_svc/order_status_service.proto

package orderbotsvcpb

import (
	context "context"
	v1 "github.com/RockkLee/order-bot/goproto/orderbot/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderStatusService_MarkOrderCompleted_FullMethodName = "/orderbot.v1.OrderStatusService/MarkOrderCompleted"
)

// OrderStatusServiceClient is the client API for OrderStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStatusServiceClient interface {
	MarkOrderCompleted(ctx context.Context, in *v1.MarkOrderCompletedRequest, opts ...grpc.CallOption) (*v1.MarkOrderCompletedResponse, error)
}

type orderStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStatusServiceClient(cc grpc.ClientConnInterface) OrderStatusServiceClient {
	return &orderStatusServiceClient{cc}
}

func (c *orderStatusServiceClient) MarkOrderCompleted(ctx context.Context, in *v1.MarkOrderCompletedRequest, opts ...grpc.CallOption) (*v1.MarkOrderCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.MarkOrderCompletedResponse)
	err := c.cc.Invoke(ctx, OrderStatusService_MarkOrderCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderStatusServiceServer is the server API for OrderStatusService service.
// All implementations must embed UnimplementedOrderStatusServiceServer
// for forward compatibility.
type OrderStatusServiceServer interface {
	MarkOrderCompleted(context.Context, *v1.MarkOrderCompletedRequest) (*v1.MarkOrderCompletedResponse, error)
	mustEmbedUnimplementedOrderStatusServiceServer()
}

// UnimplementedOrderStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStatusServiceServer struct{}

func (UnimplementedOrderStatusServiceServer) MarkOrderCompleted(context.Context, *v1.MarkOrderCompletedRequest) (*v1.MarkOrderCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkOrderCompleted not implemented")
}
func (UnimplementedOrderStatusServiceServer) mustEmbedUnimplementedOrderStatusServiceServer() {}
func (UnimplementedOrderStatusServiceServer) testEmbeddedByValue()                            {}

// UnsafeOrderStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStatusServiceServer will
// result in compilation errors.
type UnsafeOrderStatusServiceServer interface {
	mustEmbedUnimplementedOrderStatusServiceServer()
}

func RegisterOrderStatusServiceServer(s grpc.ServiceRegistrar, srv OrderStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStatusService_ServiceDesc, srv)
}

func _OrderStatusService_MarkOrderCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.MarkOrderCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderStatusServiceServer).MarkOrderCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderStatusService_MarkOrderCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderStatusServiceServer).MarkOrderCompleted(ctx, req.(*v1.MarkOrderCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderStatusService_ServiceDesc is the grpc.ServiceDesc for OrderStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderbot.v1.OrderStatusService",
	HandlerType: (*OrderStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarkOrderCompleted",
			Handler:    _OrderStatusService_MarkOrderCompleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderbot/v1/order_bot_svc/order_status_service.proto",
}
