// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: orderbot/v1/order_bot_svc/order_status_service.proto

package orderbotsvcpb

import (
	v1 "github.com/RockkLee/order-bot/goproto/orderbot/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_orderbot_v1_order_bot_svc_order_status_service_proto protoreflect.FileDescriptor

const file_orderbot_v1_order_bot_svc_order_status_service_proto_rawDesc = "" +
	"\n" +
	"4orderbot/v1/order_bot_svc/order_status_service.proto\x12\vorderbot.v1\x1a\x18orderbot/v1/common.proto2{\n" +
	"\x12OrderStatusService\x12e\n" +
	"\x12MarkOrderCompleted\x12&.orderbot.v1.MarkOrderCompletedRequest\x1a'.orderbot.v1.MarkOrderCompletedResponseBOZMgithub.com/RockkLee/order-bot/goproto/orderbot/v1/order_bot_svc;orderbotsvcpbb\x06proto3"

var file_orderbot_v1_order_bot_svc_order_status_service_proto_goTypes = []any{
	(*v1.MarkOrderCompletedRequest)(nil),  // 0: orderbot.v1.MarkOrderCompletedRequest
	(*v1.MarkOrderCompletedResponse)(nil), // 1: orderbot.v1.MarkOrderCompletedResponse
}
var file_orderbot_v1_order_bot_svc_order_status_service_proto_depIdxs = []int32{
	0, // 0: orderbot.v1.OrderStatusService.MarkOrderCompleted:input_type -> orderbot.v1.MarkOrderCompletedRequest
	1, // 1: orderbot.v1.OrderStatusService.MarkOrderCompleted:output_type -> orderbot.v1.MarkOrderCompletedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orderbot_v1_order_bot_svc_order_status_service_proto_init() }
func file_orderbot_v1_order_bot_svc_order_status_service_proto_init() {
	if File_orderbot_v1_order_bot_svc_order_status_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbot_v1_order_bot_svc_order_status_service_proto_rawDesc), len(file_orderbot_v1_order_bot_svc_order_status_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderbot_v1_order_bot_svc_order_status_service_proto_goTypes,
		DependencyIndexes: file_orderbot_v1_order_bot_svc_order_status_service_proto_depIdxs,
	}.Build()
	File_orderbot_v1_order_bot_svc_order_status_service_proto = out.File
	file_orderbot_v1_order_bot_svc_order_status_service_proto_goTypes = nil
	file_orderbot_v1_order_bot_svc_order_status_service_proto_depIdxs = nil
}
