# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbot/v1/order_bot_mgmt_svc/order_sync_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orderbot/v1/order_bot_mgmt_svc/order_sync_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orderbot.v1 import common_pb2 as orderbot_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7orderbot/v1/order_bot_mgmt_svc/order_sync_service.proto\x12\x0borderbot.v1\x1a\x18orderbot/v1/common.proto2d\n\x10OrderSyncService\x12P\n\x0b\x43reateOrder\x12\x1f.orderbot.v1.CreateOrderRequest\x1a .orderbot.v1.CreateOrderResponseBXZVgithub.com/RockkLee/order-bot/goproto/orderbot/v1/order_bot_mgmt_svc;orderbotmgmtsvcpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbot.v1.order_bot_mgmt_svc.order_sync_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/RockkLee/order-bot/goproto/orderbot/v1/order_bot_mgmt_svc;orderbotmgmtsvcpb'
  _globals['_ORDERSYNCSERVICE']._serialized_start=98
  _globals['_ORDERSYNCSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
