# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbot/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orderbot/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18orderbot/v1/common.proto\x12\x0borderbot.v1\"\x84\x01\n\tOrderItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cmenu_item_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x19\n\x11unit_price_scaled\x18\x05 \x01(\x05\x12\x1a\n\x12total_price_scaled\x18\x06 \x01(\x05\"\x98\x01\n\x12\x43reateOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rt_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x14\n\x0ctotal_scaled\x18\x05 \x01(\x05\x12%\n\x05items\x18\x06 \x03(\x0b\x32\x16.orderbot.v1.OrderItem\"!\n\x13\x43reateOrderResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"-\n\x19MarkOrderCompletedRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"(\n\x1aMarkOrderCompletedResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x42@Z>github.com/RockkLee/order-bot/goproto/orderbot/v1;orderbotv1pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbot.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/RockkLee/order-bot/goproto/orderbot/v1;orderbotv1pb'
  _globals['_ORDERITEM']._serialized_start=42
  _globals['_ORDERITEM']._serialized_end=174
  _globals['_CREATEORDERREQUEST']._serialized_start=177
  _globals['_CREATEORDERREQUEST']._serialized_end=329
  _globals['_CREATEORDERRESPONSE']._serialized_start=331
  _globals['_CREATEORDERRESPONSE']._serialized_end=364
  _globals['_MARKORDERCOMPLETEDREQUEST']._serialized_start=366
  _globals['_MARKORDERCOMPLETEDREQUEST']._serialized_end=411
  _globals['_MARKORDERCOMPLETEDRESPONSE']._serialized_start=413
  _globals['_MARKORDERCOMPLETEDRESPONSE']._serialized_end=453
# @@protoc_insertion_point(module_scope)
