// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: orderbot/v1/order_bot_mgmt_svc/order_sync_service.proto

package orderbotmgmtsvcpb

import (
	context "context"
	v1 "github.com/RockkLee/order-bot/goproto/orderbot/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderSyncService_CreateOrder_FullMethodName = "/orderbot.v1.OrderSyncService/CreateOrder"
)

// OrderSyncServiceClient is the client API for OrderSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderSyncServiceClient interface {
	CreateOrder(ctx context.Context, in *v1.CreateOrderRequest, opts ...grpc.CallOption) (*v1.CreateOrderResponse, error)
}

type orderSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderSyncServiceClient(cc grpc.ClientConnInterface) OrderSyncServiceClient {
	return &orderSyncServiceClient{cc}
}

func (c *orderSyncServiceClient) CreateOrder(ctx context.Context, in *v1.CreateOrderRequest, opts ...grpc.CallOption) (*v1.CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderSyncService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSyncServiceServer is the server API for OrderSyncService service.
// All implementations must embed UnimplementedOrderSyncServiceServer
// for forward compatibility.
type OrderSyncServiceServer interface {
	CreateOrder(context.Context, *v1.CreateOrderRequest) (*v1.CreateOrderResponse, error)
	mustEmbedUnimplementedOrderSyncServiceServer()
}

// UnimplementedOrderSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderSyncServiceServer struct{}

func (UnimplementedOrderSyncServiceServer) CreateOrder(context.Context, *v1.CreateOrderRequest) (*v1.CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderSyncServiceServer) mustEmbedUnimplementedOrderSyncServiceServer() {}
func (UnimplementedOrderSyncServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderSyncServiceServer will
// result in compilation errors.
type UnsafeOrderSyncServiceServer interface {
	mustEmbedUnimplementedOrderSyncServiceServer()
}

func RegisterOrderSyncServiceServer(s grpc.ServiceRegistrar, srv OrderSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderSyncService_ServiceDesc, srv)
}

func _OrderSyncService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSyncServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderSyncService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSyncServiceServer).CreateOrder(ctx, req.(*v1.CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderSyncService_ServiceDesc is the grpc.ServiceDesc for OrderSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderbot.v1.OrderSyncService",
	HandlerType: (*OrderSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderSyncService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderbot/v1/order_bot_mgmt_svc/order_sync_service.proto",
}
